#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "anubis"
name = "Anubis"
description.en = "Proof-of-work to stop AI crawlers"
description.fr = "Preuve de travail pour stopper les robots d'indexation de l'IA"

version = "1.14.2.~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "https://anubis.techaro.lol/"
admindoc = "https://anubis.techaro.lol/docs/admin/installation"
code = "https://github.com/TecharoHQ/anubis"
fund = "https://www.patreon.com/cadey"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/TecharoHQ/anubis/releases/download/v1.19.1/anubis_1.19.1_amd64.tar.gz"
    amd64.sha256 = "36bff879f109560e0c5f3725618c5689df14a1a965b93ca4b08747309ed97acf"
    arm64.url = "https://github.com/TecharoHQ/anubis/releases/download/v1.19.1/anubis_1.19.1_arm64.tar.gz"
    arm64.sha256 = "35a52b1e731408e4546de218a688161eb4c5f906b228166490289540ecdb7974"
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*_amd64.tar.gz"
    autoupdate.asset.arm64 = ".*_arm64.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [install.path]
    type = "path"
    default = "/anubis"

    [resources.permissions]
    main.url = "/"

    [resources.ports]
